/**
 * Achievement & Index System — Domain Definitions
 *
 * 50 achievements across 4 pillars: FAN, BAND, DJ, LABEL.
 * Each definition is the single source of truth consumed by:
 *   - The database seed (achievement_definitions table)
 *   - The granting engine (achievementEngine.ts)
 *   - The UI badge renderer (AchievementBadge component)
 *
 * Rarity tiers:
 *   COMMON    — achievable by most active users
 *   RARE      — requires sustained effort or specific conditions
 *   EPIC      — top-tier performance or long-term dedication
 *   LEGENDARY — near-impossible; true scene status markers
 */

export type AchievementPillar = 'FAN' | 'BAND' | 'DJ' | 'LABEL'
export type AchievementRarity = 'COMMON' | 'RARE' | 'EPIC' | 'LEGENDARY'

export interface AchievementDefinition {
  /** Stable identifier — never rename after release. */
  slug: string
  pillar: AchievementPillar
  rarity: AchievementRarity
  /** lucide-react icon name. */
  iconKey: string
  titleDe: string
  titleEn: string
  descDe: string
  descEn: string
  /** If true, KYC-approved status required before granting. */
  requiresKyc: boolean
  /** If true, granted automatically by the cron engine (not manually). */
  isAutomatic: boolean
}

// ─── Accent colours per pillar (for UI rendering) ────────────────────────────

export const PILLAR_COLOR: Record<AchievementPillar, string> = {
  FAN:   '#D30000',   // Blood red  — passion
  BAND:  '#7C3AED',   // Violet     — artistic prestige
  DJ:    '#00F0FF',   // Neon cyan  — technical precision
  LABEL: '#F59E0B',   // Amber gold — industry authority
}

export const RARITY_COLOR: Record<AchievementRarity, string> = {
  COMMON:    '#6B7280',
  RARE:      '#3B82F6',
  EPIC:      '#7C3AED',
  LEGENDARY: '#F59E0B',
}

// ─── All 50 Achievement Definitions ──────────────────────────────────────────

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [

  // ── FAN (15) ────────────────────────────────────────────────────────────────

  {
    slug: 'early_signal',
    pillar: 'FAN',
    rarity: 'RARE',
    iconKey: 'radio',
    titleDe: 'Early Signal',
    titleEn: 'Early Signal',
    descDe: 'Voted für einen Künstler, bevor dieser die Top-20 der Combined Charts erreichte.',
    descEn: 'Voted for an artist before they hit the Top 20 Combined Charts.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'true_believer',
    pillar: 'FAN',
    rarity: 'EPIC',
    iconKey: 'flame',
    titleDe: 'True Believer',
    titleEn: 'True Believer',
    descDe: 'Hat 100 % des monatlichen QV-Budgets auf einen einzigen Track konzentriert.',
    descEn: 'Spent 100% of the monthly QV budget on a single track.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'genre_nomad',
    pillar: 'FAN',
    rarity: 'RARE',
    iconKey: 'compass',
    titleDe: 'Genre Nomad',
    titleEn: 'Genre Nomad',
    descDe: 'Hat in einem Voting-Zyklus für Künstler aus 5+ verschiedenen Subgenres gevotet.',
    descEn: 'Voted for artists in 5+ different sub-genres within one cycle.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'verified_human',
    pillar: 'FAN',
    rarity: 'COMMON',
    iconKey: 'shield-check',
    titleDe: 'Verified Human',
    titleEn: 'Verified Human',
    descDe: '6 Monate konsistente, bot-freie Voting-Historie.',
    descEn: '6 months of consistent, bot-flag-free voting history.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'scene_veteran',
    pillar: 'FAN',
    rarity: 'RARE',
    iconKey: 'medal',
    titleDe: 'Scene Veteran',
    titleEn: 'Scene Veteran',
    descDe: 'Hat in 12 aufeinanderfolgenden monatlichen Zyklen gevotet.',
    descEn: 'Voted in 12 consecutive monthly cycles.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'alpha_listener',
    pillar: 'FAN',
    rarity: 'LEGENDARY',
    iconKey: 'star',
    titleDe: 'Alpha Listener',
    titleEn: 'Alpha Listener',
    descDe: 'Einer der ersten 100 User, die für einen Track gevotet haben, der später #1 wurde.',
    descEn: 'First 100 users to vote for a track that later hit #1.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'trend_scout',
    pillar: 'FAN',
    rarity: 'EPIC',
    iconKey: 'trending-up',
    titleDe: 'Trend Scout',
    titleEn: 'Trend Scout',
    descDe: 'Hohe Korrelation zwischen persönlichem Voting und dem Wachstum des Folgemonats.',
    descEn: 'High correlation between personal voting and following month\'s growth.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'loyalty_core',
    pillar: 'FAN',
    rarity: 'COMMON',
    iconKey: 'heart',
    titleDe: 'Loyalty Core',
    titleEn: 'Loyalty Core',
    descDe: 'Hat denselben Tier-1/2-Künstler für 3 aufeinanderfolgende Monate gevotet.',
    descEn: 'Voted for the same Tier 1/2 artist for 3 consecutive months.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'vibe_curator',
    pillar: 'FAN',
    rarity: 'COMMON',
    iconKey: 'calendar-check',
    titleDe: 'Vibe Curator',
    titleEn: 'Vibe Curator',
    descDe: 'Hat in einem Monat 10+ Partys oder Events bewertet.',
    descEn: 'Actively ranked 10+ parties or events in a single month.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'data_contributor',
    pillar: 'FAN',
    rarity: 'COMMON',
    iconKey: 'database',
    titleDe: 'Data Contributor',
    titleEn: 'Data Contributor',
    descDe: 'Profil 100 % vollständig und mit 3+ Streaming-Plattformen verknüpft.',
    descEn: 'Profile 100% complete and linked to 3+ streaming platforms.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'discovery_engine',
    pillar: 'FAN',
    rarity: 'RARE',
    iconKey: 'search',
    titleDe: 'Discovery Engine',
    titleEn: 'Discovery Engine',
    descDe: 'Hat für 10+ Tracks gevotet, die weniger als 1.000 Spotify-Listener haben.',
    descEn: 'Voted for 10+ tracks that have <1,000 Spotify listeners.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'quality_advocate',
    pillar: 'FAN',
    rarity: 'RARE',
    iconKey: 'badge-check',
    titleDe: 'Quality Advocate',
    titleEn: 'Quality Advocate',
    descDe: 'Alle gevoteteten Tracks haben einen hohen Professional-Validation-Score.',
    descEn: 'All voted tracks have a high "Professional Validation" score.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'local_hero',
    pillar: 'FAN',
    rarity: 'COMMON',
    iconKey: 'map-pin',
    titleDe: 'Local Hero',
    titleEn: 'Local Hero',
    descDe: 'Hat vorwiegend für Künstler aus der eigenen geografischen Region gevotet.',
    descEn: 'Voted primarily for artists from their own geographic region.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'bridge_builder',
    pillar: 'FAN',
    rarity: 'RARE',
    iconKey: 'globe',
    titleDe: 'Bridge Builder',
    titleEn: 'Bridge Builder',
    descDe: 'Hat in einem Zyklus für Künstler aus 3+ verschiedenen Ländern gevotet.',
    descEn: 'Voted for artists from 3+ different countries in one cycle.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'founding_fan',
    pillar: 'FAN',
    rarity: 'LEGENDARY',
    iconKey: 'crown',
    titleDe: 'Founding Fan',
    titleEn: 'Founding Fan',
    descDe: 'Account im ersten Jahr der Plattform erstellt.',
    descEn: 'Account created during the platform\'s first year.',
    requiresKyc: false,
    isAutomatic: true,
  },

  // ── BAND (15) ───────────────────────────────────────────────────────────────

  {
    slug: 'musicians_choice',
    pillar: 'BAND',
    rarity: 'LEGENDARY',
    iconKey: 'trophy',
    titleDe: 'Musician\'s Choice',
    titleEn: 'Musician\'s Choice',
    descDe: 'Platz #1 in den Band-only (Peer Review) Charts erreicht.',
    descEn: 'Reached #1 in the Band-only (Peer Review) charts.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'high_intensity_core',
    pillar: 'BAND',
    rarity: 'EPIC',
    iconKey: 'zap',
    titleDe: 'High Intensity Core',
    titleEn: 'High Intensity Core',
    descDe: 'Höchste Dichte an Super-Listenern (vollständiger QV-Budget-Einsatz).',
    descEn: 'Reached the highest density of Super-Listeners (Full QV budget spend).',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'genre_bender',
    pillar: 'BAND',
    rarity: 'EPIC',
    iconKey: 'layers',
    titleDe: 'Genre Bender',
    titleEn: 'Genre Bender',
    descDe: 'Gleichzeitig in 3+ verschiedenen Genre-Kategorien gechartet.',
    descEn: 'Charted in 3+ different genre categories simultaneously.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'honest_player',
    pillar: 'BAND',
    rarity: 'RARE',
    iconKey: 'shield',
    titleDe: 'Honest Player',
    titleEn: 'Honest Player',
    descDe: '0 % Penalty-Rate im Peer-Review-Reziprozitätscheck.',
    descEn: '0% penalty rate in the Peer-Review reciprocity check.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'velocity_star',
    pillar: 'BAND',
    rarity: 'RARE',
    iconKey: 'trending-up',
    titleDe: 'Velocity Star',
    titleEn: 'Velocity Star',
    descDe: 'Höchste SML-Wachstumsrate (Spotify Monthly Listeners) diesen Monat.',
    descEn: 'Highest growth rate in SML (Spotify Monthly Listeners) this month.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'independent_power',
    pillar: 'BAND',
    rarity: 'EPIC',
    iconKey: 'user-check',
    titleDe: 'Independent Power',
    titleEn: 'Independent Power',
    descDe: 'Top 10 ohne jegliche Label-Verbindung erreicht.',
    descEn: 'Reached Top 10 without any Label association.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'club_standard',
    pillar: 'BAND',
    rarity: 'LEGENDARY',
    iconKey: 'music-2',
    titleDe: 'Club Standard',
    titleEn: 'Club Standard',
    descDe: 'Platz #1 in den DJ-only Charts für ein Genre.',
    descEn: 'Ranked #1 in the DJ-only charts for a genre.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'global_resonance',
    pillar: 'BAND',
    rarity: 'EPIC',
    iconKey: 'globe-2',
    titleDe: 'Global Resonance',
    titleEn: 'Global Resonance',
    descDe: 'Listener aus 20+ Ländern haben für diesen Track gevotet.',
    descEn: 'Listeners from 20+ countries voted for this track.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'consistent_edge',
    pillar: 'BAND',
    rarity: 'RARE',
    iconKey: 'bar-chart-2',
    titleDe: 'Consistent Edge',
    titleEn: 'Consistent Edge',
    descDe: 'Für 6+ Monate in den Top-50 Combined Charts geblieben.',
    descEn: 'Stayed in the Top 50 Combined Charts for 6+ months.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'crowd_magnet',
    pillar: 'BAND',
    rarity: 'RARE',
    iconKey: 'users',
    titleDe: 'Crowd Magnet',
    titleEn: 'Crowd Magnet',
    descDe: 'Höchster „Event Intent"-Score für eine bevorstehende Show.',
    descEn: 'Highest "Event Intent" score for an upcoming show.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'visual_identity',
    pillar: 'BAND',
    rarity: 'COMMON',
    iconKey: 'image',
    titleDe: 'Visual Identity',
    titleEn: 'Visual Identity',
    descDe: 'Hohe Engagement-Rate auf Metadaten und Artwork-Links.',
    descEn: 'High engagement rate on metadata and artwork links.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'scene_respect',
    pillar: 'BAND',
    rarity: 'RARE',
    iconKey: 'handshake',
    titleDe: 'Scene Respect',
    titleEn: 'Scene Respect',
    descDe: 'Votes von Bands außerhalb des eigenen Label-Rosters erhalten.',
    descEn: 'Received votes from bands outside their own label roster.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'underground_king',
    pillar: 'BAND',
    rarity: 'EPIC',
    iconKey: 'skull',
    titleDe: 'Underground King',
    titleEn: 'Underground King',
    descDe: 'Tier-1-Künstler mit dem höchsten Professional-Validation-Score.',
    descEn: 'Tier 1 artist with the highest "Professional Validation" score.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'collaboration_pro',
    pillar: 'BAND',
    rarity: 'RARE',
    iconKey: 'git-merge',
    titleDe: 'Collaboration Pro',
    titleEn: 'Collaboration Pro',
    descDe: 'Mit einem Track gechartet, der 2+ registrierte Künstler featurt.',
    descEn: 'Charted with a track featuring 2+ registered artists.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'combined_champion',
    pillar: 'BAND',
    rarity: 'LEGENDARY',
    iconKey: 'crown',
    titleDe: 'Combined Champion',
    titleEn: 'Combined Champion',
    descDe: 'Platz #1 in den finalen Combined Charts erreicht.',
    descEn: 'Reached #1 in the final Combined Charts.',
    requiresKyc: false,
    isAutomatic: true,
  },

  // ── DJ (10) ─────────────────────────────────────────────────────────────────

  {
    slug: 'predictive_authority',
    pillar: 'DJ',
    rarity: 'EPIC',
    iconKey: 'brain',
    titleDe: 'Predictive Authority',
    titleEn: 'Predictive Authority',
    descDe: 'Schulze-Rankings stimmen mit den Fan-Charts des Folgemonats überein.',
    descEn: 'Schulze rankings match the next month\'s Fan-Charts.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'technical_critic',
    pillar: 'DJ',
    rarity: 'RARE',
    iconKey: 'message-square',
    titleDe: 'Technical Critic',
    titleEn: 'Technical Critic',
    descDe: 'Qualitativ hochwertiges Feedback für 20+ Künstler gegeben.',
    descEn: 'Provided qualitatively high feedback for 20+ artists.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'reliable_curator',
    pillar: 'DJ',
    rarity: 'RARE',
    iconKey: 'calendar-check',
    titleDe: 'Reliable Curator',
    titleEn: 'Reliable Curator',
    descDe: '100 % Voting-Teilnahme über 12 Monate.',
    descEn: '100% voting participation over 12 months.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'venue_pillar',
    pillar: 'DJ',
    rarity: 'EPIC',
    iconKey: 'building-2',
    titleDe: 'Venue Pillar',
    titleEn: 'Venue Pillar',
    descDe: 'Verifizierte Residency in einem Top-10-Club/Venue.',
    descEn: 'Verified residency at a Top 10 ranked Club/Venue.',
    requiresKyc: true,
    isAutomatic: false,
  },
  {
    slug: 'first_responder',
    pillar: 'DJ',
    rarity: 'LEGENDARY',
    iconKey: 'alert-triangle',
    titleDe: 'First Responder',
    titleEn: 'First Responder',
    descDe: 'Erster DJ, der einen Track gerankt hat, der später zum "Club Standard" wurde.',
    descEn: 'First DJ to rank a track that eventually became a "Club Standard".',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'master_of_paths',
    pillar: 'DJ',
    rarity: 'EPIC',
    iconKey: 'git-branch',
    titleDe: 'Master of Paths',
    titleEn: 'Master of Paths',
    descDe: 'Die vollständige Schulze-Liste (n-Ranking) für 5+ Genres genutzt.',
    descEn: 'Utilized the full Schulze list (n-ranking) for 5+ genres.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'industry_insider',
    pillar: 'DJ',
    rarity: 'RARE',
    iconKey: 'briefcase',
    titleDe: 'Industry Insider',
    titleEn: 'Industry Insider',
    descDe: 'Feedback von 10+ Künstlern als „Highly Useful" markiert.',
    descEn: 'Feedback flagged as "Highly Useful" by 10+ artists.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'floor_filler',
    pillar: 'DJ',
    rarity: 'RARE',
    iconKey: 'music',
    titleDe: 'Floor Filler',
    titleEn: 'Floor Filler',
    descDe: 'Gevotetete Tracks zeigen die höchsten Spotify-Save-Konversionsraten.',
    descEn: 'Voted tracks show highest "Spotify Save" conversion rates.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'diverse_ear',
    pillar: 'DJ',
    rarity: 'RARE',
    iconKey: 'headphones',
    titleDe: 'Diverse Ear',
    titleEn: 'Diverse Ear',
    descDe: 'Expertenstatus in 3+ fundamental verschiedenen Subgenres.',
    descEn: 'Expert status in 3+ fundamentally different sub-genres.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'legacy_curator',
    pillar: 'DJ',
    rarity: 'LEGENDARY',
    iconKey: 'clock',
    titleDe: 'Legacy Curator',
    titleEn: 'Legacy Curator',
    descDe: 'Aktiver DJ in der Szene seit 10+ Jahren (KYC-verifiziert).',
    descEn: 'Active DJ in the scene for 10+ years (verified via KYC).',
    requiresKyc: true,
    isAutomatic: false,
  },

  // ── LABEL (10) ──────────────────────────────────────────────────────────────

  {
    slug: 'ar_vanguard',
    pillar: 'LABEL',
    rarity: 'LEGENDARY',
    iconKey: 'rocket',
    titleDe: 'A&R Vanguard',
    titleEn: 'A&R Vanguard',
    descDe: '3+ Acts gesignt, die im Top-10-Velocity-Index waren.',
    descEn: 'Signed 3+ acts that were in the Top 10 "Velocity Index".',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'newcomer_engine',
    pillar: 'LABEL',
    rarity: 'EPIC',
    iconKey: 'sparkles',
    titleDe: 'Newcomer Engine',
    titleEn: 'Newcomer Engine',
    descDe: 'Label mit den meisten Einträgen in Tier 1 und Tier 2.',
    descEn: 'Label with the most entries in Tier 1 and Tier 2.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'efficiency_pro',
    pillar: 'LABEL',
    rarity: 'RARE',
    iconKey: 'bar-chart',
    titleDe: 'Efficiency Pro',
    titleEn: 'Efficiency Pro',
    descDe: 'Höchste Erfolg-zu-Roster-Ratio in den Combined Charts.',
    descEn: 'Highest success-to-roster ratio in the Combined Charts.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'transparent_partner',
    pillar: 'LABEL',
    rarity: 'COMMON',
    iconKey: 'eye',
    titleDe: 'Transparent Partner',
    titleEn: 'Transparent Partner',
    descDe: 'Alle RLS-Mandate sind aktiv, verifiziert und einwandfrei.',
    descEn: 'All RLS mandates are active, verified, and clean.',
    requiresKyc: true,
    isAutomatic: true,
  },
  {
    slug: 'scene_catalyst',
    pillar: 'LABEL',
    rarity: 'RARE',
    iconKey: 'zap',
    titleDe: 'Scene Catalyst',
    titleEn: 'Scene Catalyst',
    descDe: 'Eine „Best Party of the Month"-Gewinner-Veranstaltung organisiert/unterstützt.',
    descEn: 'Organized/Supported a "Best Party of the Month" winner.',
    requiresKyc: false,
    isAutomatic: false,
  },
  {
    slug: 'territory_lead',
    pillar: 'LABEL',
    rarity: 'RARE',
    iconKey: 'globe',
    titleDe: 'Territory Lead',
    titleEn: 'Territory Lead',
    descDe: 'Label mit den meisten internationalen (grenzüberschreitenden) Chart-Einträgen.',
    descEn: 'Label with the most international (cross-border) chart entries.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'market_mover',
    pillar: 'LABEL',
    rarity: 'EPIC',
    iconKey: 'trending-up',
    titleDe: 'Market Mover',
    titleEn: 'Market Mover',
    descDe: 'Label, dessen Künstler die meiste Super-Listener-Aktivität generiert haben.',
    descEn: 'Label whose artists generated the most "Super-Listener" activity.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'sustainability_star',
    pillar: 'LABEL',
    rarity: 'EPIC',
    iconKey: 'leaf',
    titleDe: 'Sustainability Star',
    titleEn: 'Sustainability Star',
    descDe: '5+ Acts über mehr als ein Jahr in den Top 100 gehalten.',
    descEn: 'Maintained 5+ acts in the Top 100 for over a year.',
    requiresKyc: false,
    isAutomatic: true,
  },
  {
    slug: 'b2b_networker',
    pillar: 'LABEL',
    rarity: 'RARE',
    iconKey: 'network',
    titleDe: 'B2B Networker',
    titleEn: 'B2B Networker',
    descDe: 'Mandate für 10+ verschiedene Bands über das RLS-System verwaltet.',
    descEn: 'Successfully managed mandates for 10+ different bands via RLS.',
    requiresKyc: true,
    isAutomatic: true,
  },
  {
    slug: 'industrial_excellence',
    pillar: 'LABEL',
    rarity: 'LEGENDARY',
    iconKey: 'award',
    titleDe: 'Industrial Excellence',
    titleEn: 'Industrial Excellence',
    descDe: 'Insgesamt höchste professionelle Bewertung im DaaS-Dashboard.',
    descEn: 'Overall highest professional rating across the DaaS-Dashboard.',
    requiresKyc: true,
    isAutomatic: true,
  },
]

/** Look up a single definition by slug — throws if not found. */
export function getAchievementBySlug(slug: string): AchievementDefinition {
  const def = ACHIEVEMENT_DEFINITIONS.find((d) => d.slug === slug)
  if (!def) throw new Error(`Achievement definition not found: ${slug}`)
  return def
}

/** Filter definitions by pillar. */
export function getAchievementsByPillar(pillar: AchievementPillar): AchievementDefinition[] {
  return ACHIEVEMENT_DEFINITIONS.filter((d) => d.pillar === pillar)
}
